name: frs

environment:
  sdk: ">=3.5.4 <4.0.0"

dev_dependencies:
  melos: ^6.2.0
  rps: ^0.7.0

scripts:
  backend:
    start: |
      cd packages/backend
      arcade serve
    gen: |
      cd packages/backend
      dart run build_runner watch --delete-conflicting-outputs
    gen:clean: |
      (cd packages/backend
        dart run build_runner clean)
      dart run rps backend gen

  frontend:
    gen: |
      cd apps/frontend
      fvm dart run build_runner watch --delete-conflicting-outputs
    gen:clean: |
      (cd apps/frontend
        fvm dart run build_runner clean)
      dart run rps frontend gen
