version: '3'

tasks:
  backend:gen:clean:
    dir: packages/backend
    cmds:
      - clear
      - dart run build_runner clean
  backend:gen:
    dir: packages/backend
    cmds:
      - clear
      - dart run build_runner watch --delete-conflicting-outputs
  backend:serve:
    dir: packages/backend
    cmds:
      - clear
      - arcade serve
