name: backend
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  arcade: ^0.2.2
  drift: ^2.21.0
  drift_hrana: ^1.0.3
  envied: ^0.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  luthor: ^0.4.3
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.21.0
  envied_generator: ^0.5.4
  freezed: ^2.5.7
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lint: ^2.3.0
  luthor_generator: ^0.4.6
